AWSTemplateFormatVersion: 2010-09-09
Description: >-
  order-management-service code

Transform:
- AWS::Serverless-2016-10-31

Resources:            
  orderDispatchedHandler:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: app/
      Handler: dist/src/handlers/order-dispatched-event-handler.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: Handle an order dispatched event from the event bus.
      Events:
        Trigger:
          Type: CloudWatchEvent 
          Properties:
            Pattern:
              source:
                - com.kitchen
              detail-type:
                - order-dispatched
            
  startOrderAcceptance:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: app/
      Handler: dist/src/handlers/start-order-acceptance.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: Sets up initial state orchestration for order acceptance
            
  stockChecker:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: app/
      Handler: dist/src/handlers/stock-checker.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: Stock checker function used in order acceptance step function.
            
  paymentProcessor:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: app/
      Handler: dist/src/handlers/payment-processor.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: Payment processing function used in order acceptance step function.
            
  orderAcceptanceResult:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: app/
      Handler: dist/src/handlers/order-acceptance-result.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: Result handler for processing stock and payment results used in order acceptance step function.
      
  OrderAcceptanceStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: app/dist/src/infrastructure/state-machine/order-acceptance.asl.json
      DefinitionSubstitutions:
        StartOrderAcceptanceFunctionArn: !GetAtt startOrderAcceptance.Arn
        StockCheckerFunctionArn: !GetAtt stockChecker.Arn
        PaymentProcessorFunctionArn: !GetAtt paymentProcessor.Arn
        OrderAcceptanceResultFunctionArn: !GetAtt orderAcceptanceResult.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref startOrderAcceptance
        - LambdaInvokePolicy:
            FunctionName: !Ref stockChecker
        - LambdaInvokePolicy:
            FunctionName: !Ref paymentProcessor
        - LambdaInvokePolicy:
            FunctionName: !Ref orderAcceptanceResult

  OrderAcceptanceEventIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                  - Fn::Sub: "events.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: StateMachineExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "states:StartExecution"
                Resource:
                  - !Ref OrderAcceptanceStateMachine

  OrderCreatedEventRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: "Event rule to trigger for order created events and start the acceptance state machine"
      Name: 'OrderCreatedEventRule'
      EventPattern:
        source:
          - com.order-management
        detail-type:
          - order-created
      State: "ENABLED"
      Targets:
        -
          Arn: !Ref OrderAcceptanceStateMachine
          Id: !GetAtt OrderAcceptanceStateMachine.Name
          RoleArn: !GetAtt OrderAcceptanceEventIAMRole.Arn
